# Generated by Django 4.0.2 on 2022-05-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact_name_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linkedin_id',
            field=models.URLField(default='', max_length=100),
        ),
    ]
