# Generated by Django 4.0.2 on 2022-05-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_contact_linkedin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Job_Role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='Passout_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
